import type { Plugin } from "vite";
import fs from "fs/promises";
import path from "path";

export function autoRoutesPlugin(): Plugin {
  const pagesDir = path.resolve(process.cwd(), "src/pages");
  const outputFile = path.resolve(pagesDir, "index.tsx");

  async function scanRouteFiles(): Promise<string[]> {
    const routeFiles: string[] = [];

    async function scanDir(dir: string) {
      try {
        const entries = await fs.readdir(dir, { withFileTypes: true });

        for (const entry of entries) {
          const fullPath = path.join(dir, entry.name);

          if (entry.isDirectory()) {
            // Check if the directory contains route_data.tsx
            const routeDataPath = path.join(fullPath, "route_data.tsx");
            try {
              await fs.access(routeDataPath);
              // Found a route_data.tsx file
              const relativePath = path.relative(pagesDir, fullPath);
              const importName = `${relativePath.replace(/[\\/]/g, "_")}_routes`;
              routeFiles.push(
                `import { ${relativePath.replace(/[\\/]/g, "_")}Routes as ${importName} } from './${relativePath}/route_data';`,
              );
            } catch {
              // No route_data.tsx in this directory, continue scanning
              await scanDir(fullPath);
            }
          }
        }
      } catch (error) {
        console.error(`Error scanning directory ${dir}:`, error);
      }
    }

    await scanDir(pagesDir);
    return routeFiles;
  }

  async function generateIndexFile() {
    try {
      await fs.mkdir(pagesDir, { recursive: true });
      const imports = await scanRouteFiles();

      if (imports.length === 0) {
        const defaultContent = `
const allRoutes = [];
export default allRoutes;
`;
        await fs.writeFile(outputFile, defaultContent, "utf-8");
        return;
      }

      // Generate the complete file content
      const content = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by vite-plugin-auto-routes

${imports.join("\n")}

const allRoutes = [
${imports
  .map((imp) => {
    const match = imp.match(/as (\w+)/);
    return match ? `  ...${match[1]},` : "";
  })
  .filter(Boolean)
  .join("\n")}
];

export default allRoutes;
`;

      await fs.writeFile(outputFile, content, "utf-8");
      console.log("✅ Auto-generated routes index.tsx");
    } catch (error) {
      console.error("Error generating routes index.tsx:", error);
    }
  }

  return {
    name: "vite-plugin-auto-routes",

    buildStart: async () => {
      await generateIndexFile();
    },
    configureServer(server) {
      server.watcher.add(path.join(pagesDir, "**/route_data.tsx"));

      server.watcher.on("change", async (changedPath) => {
        if (changedPath.includes("route_data.tsx")) {
          console.log(`🔄 Route file changed: ${changedPath}`);
          await generateIndexFile();
          // Trigger HMR update for the routes file
          const module = server.moduleGraph.getModuleById(outputFile);
          if (module) {
            server.reloadModule(module);
          }
        }
      });

      // Also watch for new directories being added
      server.watcher.add(pagesDir);
      server.watcher.on("addDir", async (dirPath) => {
        const routeDataPath = path.join(dirPath, "route_data.tsx");
        try {
          await fs.access(routeDataPath);
          await generateIndexFile();
        } catch {
          // No route_data.tsx in new directory
        }
      });
    },
    buildEnd: async () => {
      await generateIndexFile();
    },
  };
}
