// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by vite-plugin-auto-routes

import { clientRoutes as client_routes } from '@/pages/client/route_data';
import { homeRoutes as home_routes } from '@/pages/home/route_data';

const allRoutes = [
  ...client_routes,
  ...home_routes,
];

export default allRoutes;
